### ISSUE TITLE
Useful links

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/hotel-booking#2]
I leave here some useful links for our project:

- Main links:

    - [Mezidia's Trello](https://trello.com/invite/mezidia/af6e351847070ce6cdf2fe663f28916a)
    - [Tool for diagrams](https://creately.com/)
    - [Report on NoSQL](https://docs.google.com/document/d/1gBSu_EyV9RDRXgcmw9BVWABVv4856fBS_l74ducCzMc/edit?usp=sharing)
    - [Link on NoSQL presentation](https://docs.google.com/presentation/d/1sgLDEwKNBNQm3jWSs4NFBS4upq4ntCt6ch9m3DnxEsE/edit?usp=sharing)
- Lessons  and resources links:

    - [Using .NET Core in Visual Studio Code(in English)](https://code.visualstudio.com/docs/languages/dotnet)
    - [C# lessons(in Russian)](https://www.youtube.com/playlist?list=PL0lO_mIqDDFU66Cwwctcv1C6VNVpaqHfo)
    - [C# lessons(in Russian) 2](https://www.youtube.com/playlist?list=PLuGqgO5WmeGPTZqDHZDIum3h7HnfBfzmZ)
    - [Lessons on Metanit(in Russian)](https://metanit.com/sharp/)
    - [Basic Database Operations Using C#(in English)](https://www.geeksforgeeks.org/basic-database-operations-using-c-sharp/)
    - [Microsoft.Data.Sqlite overview(in Russian)](https://docs.microsoft.com/ru-ru/dotnet/standard/data/sqlite/?tabs=netcore-cli)
    - [C# + MS SQL Server(in Russian)](https://metanit.com/sharp/adonet/2.13.php)
    - [Booking.com API(in English)](https://developers.booking.com/api/index.html)

- [ASP.NET Core](https://uk.wikipedia.org/wiki/ASP.NET_Core):

    - [MVC 5 with Unity for Dependency Injection(in English)](http://sarangasl.blogspot.com/2015/04/mvc-5-with-unity-for-dependency.html)
    - [Creating Simple Grid in MVC Using Grid.MVC(in English)](https://www.c-sharpcorner.com/UploadFile/4d9083/creating-simple-grid-in-mvc-using-grid-mvc/)

> If you want to add something, write **it** down in comments, I'll add to this message

**Comment by VsIG-official** [comment]
https://metanit.com/sharp/

**Comment by VsIG-official** [comment]
(in russian)

**Comment by VsIG-official** [comment]
https://www.youtube.com/playlist?list=PLPV2KyIb3jR4CtEelGPsmPzlvP7ISPYzR
Really basic stuff, so don't sure, should We add this

**Comment by mezgoodle** [comment]
> https://www.youtube.com/playlist?list=PLPV2KyIb3jR4CtEelGPsmPzlvP7ISPYzR
> Really basic stuff, so don't sure, should We add this

itProger has more

**Comment by VsIG-official** [comment]
https://www.youtube.com/playlist?list=PLuGqgO5WmeGPTZqDHZDIum3h7HnfBfzmZ

**Comment by VsIG-official** [comment]
https://trello.com/invite/mezidia/af6e351847070ce6cdf2fe663f28916a

**Comment by mezgoodle** [comment]
> https://trello.com/invite/mezidia/af6e351847070ce6cdf2fe663f28916a

thank you

**Comment by mezgoodle** [comment]
add link for MS SQL Server + C#

**Comment by mezgoodle** [comment]
> http://sarangasl.blogspot.com/2015/04/mvc-5-with-unity-for-dependency.html
> https://www.c-sharpcorner.com/UploadFile/4d9083/creating-simple-grid-in-mvc-using-grid-mvc/
> for creation grid & working with DI (dependency invertion)

Thank you for these articles, **especially** for me, because I'm trying to do UI with _ASP.NET_, but I do this in [VSC](https://code.visualstudio.com/). I will add these links **anyway**

**Comment by La7rodectus** [comment]
https://creately.com/

**Comment by lizardlynx** [comment]
Link on NoSQL presentation: https://docs.google.com/presentation/d/1sgLDEwKNBNQm3jWSs4NFBS4upq4ntCt6ch9m3DnxEsE/edit?usp=sharing
